apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: enonic
  labels:
    app: xp
    role: frontend
spec:
  ports:
    - port: 2609
      name: http-svc-monitoring
      targetPort: http-monitoring
  selector:
    app: xp
    role: frontend
  type: LoadBalancer
