apiVersion: v1
kind: PersistentVolume
metadata:
  name: enonic-xp-snapshot-pv-volume
  labels:
    type: local
spec:
  storageClassName: fast-snapshot
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/davborre/Source/enonic-xp/storage/snapshots"
