language: generic
group: container
env:
  global:
    - APPLICATION_NAME=enonic-xp
    - GIT_RESET_IF_BRANCH=${GIT_RESET_IF_BRANCH:-release}
    - GIT_RESET_BRANCH=${GIT_RESET_BRANCH:-develop}
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - TF_VERSION=1.0.10
    - TF_ARTIFACTS_S3=sch-cbt-iaac
    - TF_ARTIFACTS_REGION=eu-central-1
    - TF_VAR_docker_dir=$TRAVIS_BUILD_DIR/docker
    # AWS_ACCESS_KEY_ID
    - secure: "hS5fsJdlFzpq5omzLL1/i3l1mWYtsj2pZDIutbsXtWmey1CK5+HCtmVGk+DGTkF/41P457M+MHYiH5h+5us7nB1PqznqMV6U+Lq9DjjTBmbuVDSeyv64LJGiR6CLk7Msc781ptOaTPKUvHfALHD46eN9ke81qMERbQKdLV8t+L3P38hqmKMNPYBOWwOTsMEaJ2eG+8ZfNc0aXpehVMX/Yc+NjZ5UlDbL1feuL+Ac96PWgNzSEt9bYhRrpCy2/UcPDwyOKdLO4nmMSAVHOLT5W39WyM/H8U8v4PYVmL/9Ij1o2cP0/qGu+ieGOHOXTZWWHwFSDofiPVlzSzh1N+MsHFbpLLK1gCsRZAR2OcvrjGd7knXObF+NbplKf8IK1ymM0OkDzxHKz8M774G8vKV2O6lnzpN48tovo8U2zHrV3IAVWN8v2Uj7nAPhp5GNhdyM1YNmI7zatqIZS1auHK1hlRjFw0jm0otJ6qdurWMqfL1ZdH1tZ40HUjOs5j2zkcmr/FwGysy8ijLqKWIHXCZLm7gvCmmhCZoTOQYd4HjafRieQyzIaTA8yhlqnZlaTdFmEs+i+oMp37GBGUxw9YaXrOAHOTFetkGD5NvaMG29Md5kVZl+vrq/wnjzixpnBy5bEnPWFuvjSv5Szc8AZCtVGttSk6erNj2fhBu4YiRsnBg="
    # AWS_SECRET_ACCESS_KEY
    - secure: "rQgnr/h9/8Gn6HLbAGdIjZ8ks7rs+fPdtX5fVq/j2RKKzjAU8B3MLLjx+krjD/gKnYDc3NGlGcOV6s6JOWyJsiSH0mpDUtgd5htUpxrJLH2ydSkbJ4PRgQ/AfAqmU0coFKyO0pZCzllqJR7VIbypcEWPg2uZuZJHHl3EZrQzXOqkni0bedtyq6A5Fc8lcMlStjJtMCN1Q4QJYqJCD+mf6Q8D0SoUH3knRVTjegRiKlMCr/Z4PyfMOO292qYTY97HSd+7D+HrraPe2oNrdpCANX1RdXFgdnBu1DfwnmnEgSIaoFOC+ed2hUEThRNZrwYUKaGEnv0R4kHLU+GAohezkmch6uQhYFoG3LZZJ6EHC/sxcwZNMsnicd6wO+MB+d2BmPy0BHfVkQ0avFZXisCWlgM9VMVMY2C34Efns4h5CVwkJDHjz3CXSfmHCrMn+L4c2zDr3khkebviEQd2+iWHYI82LGZCRsbrEcJg8KbJYz85UhN9qCTQL437amVJJCTN0Sam9I+szDH9o2uJMkqmh5Bwgw34gNJzWHU2bJo+9Yu8oHABpWjomS9wZ0wGRz2Wxl4TGeinXfRxH+WSdL3c/FLTlo+MHazgc2z33F53RdzD4MUJ3AwiTPCscYRu7CWBaiItHYtj8XNi4SKIjkwiszqMVfbRrS5nOh75XhIMWyU="

_commons:
  validate: &stageValidate
    # Required: not a fork
    # Either:
    # - Any pull request
    # - Not a master branch (includes tags)
    if: fork = false AND tag IS blank AND ( type = pull_request OR ( type = push AND branch != "master" ) )
    before_install: *onlyOnProperBranch
    script: ./infrastructure/bin/run.sh test enonic-xp $WORK_DIRS || travis_terminate 1

  plan: &stagePlan
    # Required: not a fork
    # Either:
    # - A commit to master
    # - A pull request to master
    if: fork = false AND ( branch = "master" OR branch = "feature/terraform" ) AND ( type = push OR type = pull_request )
    before_install: *onlyOnProperBranch
    script: ./infrastructure/bin/run.sh plan enonic-xp $WORK_DIRS || travis_terminate 1

  apply: &stageApply
    # Required:
    # - not a fork
    # - a commit
    # - Either apply/domain/ or apply/global/ tag.
    script: ./infrastructure/bin/run.sh apply enonic-xp $WORK_DIRS || travis_terminate 1

## Pipeline configuration
jobs:
  include:
    # On: branches, PRs
    - stage: VALIDATE
      <<: *stageValidate
      env:
        - WORK_DIRS="infrastructure/stage infrastructure/prod infrastructure/shared"
    - stage: BUILD
      if: fork = false AND ( branch = "master" OR branch = "feature/terraform" ) AND type = push
      script:
        - ./infrastructure/bin/run.sh plan enonic-xp infrastructure/shared || travis_terminate 1
        - ./infrastructure/bin/run.sh apply enonic-xp infrastructure/shared || travis_terminate 1
      deploy:
        provider: script
        script: docker/build_push.sh ./docker  $(pushd -q infrastructure/shared && terraform output -raw docker_image && popd -q) $TRAVIS_COMMIT
        on:
          all_branches: true
    - stage: PLAN
      <<: *stagePlan
      env:
        - WORK_DIRS="infrastructure/stage"
    - stage: APPLY
      if: tag =~ ^(apply\/).+ AND fork = false AND type = push
      <<: *stageApply
      env:
        - WORK_DIRS="infrastructure/stage"

