language: generic
group: container
env:
  global:
    - APPLICATION_NAME=enonic-xp
    - GIT_RESET_IF_BRANCH=${GIT_RESET_IF_BRANCH:-release}
    - GIT_RESET_BRANCH=${GIT_RESET_BRANCH:-develop}
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - TF_VERSION=1.0.10
    - TF_ARTIFACTS_S3=sch-cbt-iaac
    - TF_ARTIFACTS_REGION=eu-central-1
    - TF_VAR_docker_dir=$TRAVIS_BUILD_DIR/docker
    - TF_VAR_commit=$TRAVIS_COMMIT
    - TV_VAR_XP_OPTS="-XX:MinRAMPercentage=75 -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=5"
    - ECR_ENONIC=953355806585.dkr.ecr.eu-central-1.amazonaws.com/enonic-xp
    - TF_VAR_enonic_docker_image=${ECR_ENONIC}:${TRAVIS_COMMIT}
    # AWS_ACCESS_KEY_ID
    - secure: "hS5fsJdlFzpq5omzLL1/i3l1mWYtsj2pZDIutbsXtWmey1CK5+HCtmVGk+DGTkF/41P457M+MHYiH5h+5us7nB1PqznqMV6U+Lq9DjjTBmbuVDSeyv64LJGiR6CLk7Msc781ptOaTPKUvHfALHD46eN9ke81qMERbQKdLV8t+L3P38hqmKMNPYBOWwOTsMEaJ2eG+8ZfNc0aXpehVMX/Yc+NjZ5UlDbL1feuL+Ac96PWgNzSEt9bYhRrpCy2/UcPDwyOKdLO4nmMSAVHOLT5W39WyM/H8U8v4PYVmL/9Ij1o2cP0/qGu+ieGOHOXTZWWHwFSDofiPVlzSzh1N+MsHFbpLLK1gCsRZAR2OcvrjGd7knXObF+NbplKf8IK1ymM0OkDzxHKz8M774G8vKV2O6lnzpN48tovo8U2zHrV3IAVWN8v2Uj7nAPhp5GNhdyM1YNmI7zatqIZS1auHK1hlRjFw0jm0otJ6qdurWMqfL1ZdH1tZ40HUjOs5j2zkcmr/FwGysy8ijLqKWIHXCZLm7gvCmmhCZoTOQYd4HjafRieQyzIaTA8yhlqnZlaTdFmEs+i+oMp37GBGUxw9YaXrOAHOTFetkGD5NvaMG29Md5kVZl+vrq/wnjzixpnBy5bEnPWFuvjSv5Szc8AZCtVGttSk6erNj2fhBu4YiRsnBg="
    # AWS_SECRET_ACCESS_KEY
    - secure: "rQgnr/h9/8Gn6HLbAGdIjZ8ks7rs+fPdtX5fVq/j2RKKzjAU8B3MLLjx+krjD/gKnYDc3NGlGcOV6s6JOWyJsiSH0mpDUtgd5htUpxrJLH2ydSkbJ4PRgQ/AfAqmU0coFKyO0pZCzllqJR7VIbypcEWPg2uZuZJHHl3EZrQzXOqkni0bedtyq6A5Fc8lcMlStjJtMCN1Q4QJYqJCD+mf6Q8D0SoUH3knRVTjegRiKlMCr/Z4PyfMOO292qYTY97HSd+7D+HrraPe2oNrdpCANX1RdXFgdnBu1DfwnmnEgSIaoFOC+ed2hUEThRNZrwYUKaGEnv0R4kHLU+GAohezkmch6uQhYFoG3LZZJ6EHC/sxcwZNMsnicd6wO+MB+d2BmPy0BHfVkQ0avFZXisCWlgM9VMVMY2C34Efns4h5CVwkJDHjz3CXSfmHCrMn+L4c2zDr3khkebviEQd2+iWHYI82LGZCRsbrEcJg8KbJYz85UhN9qCTQL437amVJJCTN0Sam9I+szDH9o2uJMkqmh5Bwgw34gNJzWHU2bJo+9Yu8oHABpWjomS9wZ0wGRz2Wxl4TGeinXfRxH+WSdL3c/FLTlo+MHazgc2z33F53RdzD4MUJ3AwiTPCscYRu7CWBaiItHYtj8XNi4SKIjkwiszqMVfbRrS5nOh75XhIMWyU="

## Pipeline configuration
jobs:
  include:
    # On: branches, PRs
    - stage: VALIDATE
      if: fork = false AND tag IS blank AND ( type = pull_request OR ( type = push AND branch != "master" ) )
      script: ./infrastructure/bin/run.sh test enonic-xp $WORK_DIRS || travis_terminate 1
      env:
        - WORK_DIRS="infrastructure/stage infrastructure/prod infrastructure/shared"

    - stage: BUILD
      if: tag =~ ^(infra\/).+ AND fork = false AND type = push
      env:
        - PKR_VAR_assume_role=arn:aws:iam::953355806585:role/cicd/ma-fulladmin
        # PKR_VAR_CID
        - secure: "DI9S0ZSzo5jSNhrzNmLdobZGvsHPx5oIP1W6qUsHUj4PSw8I1NLUhQ7/y5Lx9N+ZU1XJRDPXDbPIyI0jMQqP0rCljbCmFKPriuf4LPI2Eo4LJ+jZ7EzyWrptvU5rHV1c99qT1y/9Yr6mjyQSu/dNCdQi/grJudTOrRsak5Mh3Z1huXXgzkaERcDCv8JTxem/trdMFwHOeE2XbQVaEhu0N0cI+89++nKnjbuAFhQUik/Xl4nrocCHTtSxq8wiIVJ4hUGiejm0pTAHyhqiA/pxImPhW9CpdtLlRJtmMQUZtUqkPjAPsmrJbM8+xhOc+VGcHDIGViUHduM3zEEChhiyF/cfqG4yk31QZhFEnBHS1aYmWl7kE9uGHLRitKvLEqfAiAmQsZ8sfnNChAoFeb6EjIz5NlMyqKqnp+h7LHlhBTuimZZ75xc1xPmtz+fwnC6QeuXAUr40XZTBhqTSUz/lH2viZb+SyVAcg7lSspFkgTw5UpBcnYX5mTHVXsq+BHaKckYUuEkJpaWFXTkRv2isnHtyYOSCdaqo/Y2W+besm0otdtdIg8XWGhwp20q7kXYRGJErRpYVwU+buXZDr7iqYuN5KdrixAg2Kx/NpbBao6NRNOKOWPmGiLSDvE7/r1dgXlVpyrrkbJpl9fc/FiR40/5t/DLMUD+3/rrXcJZXGP0="
      before_script:
        - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        - sudo apt-get update && sudo apt-get install packer
      script:
        - ./infrastructure/bin/build_ami.sh || travis_terminate 1
        - ./infrastructure/bin/run.sh plan enonic-xp infrastructure/shared || travis_terminate 1
        - ./infrastructure/bin/run.sh apply enonic-xp infrastructure/shared || travis_terminate 1

    - stage: BUILD
      if: tag IS blank
      group: vm
      services:
        - docker
      env:
        - ASSUME_ROLE=arn:aws:iam::953355806585:role/cicd/ma-fulladmin
      deploy:
        provider: script
        script: npx -y depstrive execWithAssume -l info -r $ASSUME_ROLE -- docker/build_push.sh ./docker $ECR_ENONIC $TRAVIS_COMMIT
        on:
          all_branches: true

    - stage: PLAN
      if: fork = false AND ( branch = "master" OR branch = "feature/terraform" OR tag =~ ^(infra\/).+ ) AND ( type = push OR type = pull_request )
      script: ./infrastructure/bin/run.sh plan enonic-xp $WORK_DIRS || travis_terminate 1
      env:
        - WORK_DIRS="infrastructure/stage"

    - stage: APPLY
      if: tag =~ ^(apply\/).+ AND fork = false AND type = push
      script: ./infrastructure/bin/run.sh apply enonic-xp $WORK_DIRS || travis_terminate 1
      env:
        - WORK_DIRS="infrastructure/stage"
