apiVersion: v1
kind: PersistentVolume
metadata:
  name: enonic-xp-blob-pv-volume
  namespace: enonic
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.76.101.170
    path: "/filestore_nfs/enonic-cluster-stage/repo/blob"
