apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "enonic"

bases:
  - ../../base

resources:
  - ./storage/pv-snapshots.yaml
  - ./storage/pv-data.yaml
  - ./storage/pv-blob.yaml
