apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: enonic
  labels:
    app: xp
    role: frontend
spec:
  ports:
    - port: 8080
      name: http-svc-enonic
      targetPort: http-enonic
  selector:
    app: xp
    role: frontend
  type: LoadBalancer
